In [12]:
import pandas as pd
import nltk
from nltk import word_tokenize,sent_tokenize,RegexpTokenizer
from nltk.corpus import stopwords
import re
from nltk.stem import WordNetLemmatizer,PorterStemmer 
from textblob import TextBlob
import string

In [13]:

data = pd.read_csv('f_dataf.csv')

data = data.drop(columns=['Unnamed: 0'])


data.head()




Caption  Total_reactions  \
0  Donald J. Trump's debate study habits, Hillary...               58   
1  Since 1956, no presidential candidate has won ...               33   
2  "Only when his handlers tied him down and forc...              497   
3  A manufactured storyline. A promise of a "majo...               81   
4  "There's a reason why we haven't had a woman p...              513   

   No_of_Comment  Share                                            Comment  \
0            103      8                        Name                    ...   
1             64      6                           Name  \\n0   Francisc...   
2            383    111                       Name                     ...   
3            123     17                       Name                     ...   
4            331    116                       Name                     ...   

                              Reaction  \
0     ['51 Like', '3 Haha', '3 Angry']   
1                ['31 Like', '2 Love']   
2  ['417 Like', '42 Love', '21 Angry']   
3   ['59 Like', '12 Angry', '10 Haha']   
4   ['462 Like', '25 Love', '12 Haha']   

                                            Post_url       Rating  Like  Haha  \
0  https://www.facebook.com/cnnpolitics/posts/128...  mostly true    51     3   
1  https://www.facebook.com/cnnpolitics/posts/128...  mostly true    31     0   
2  https://www.facebook.com/cnnpolitics/posts/128...  mostly true   417     0   
3  https://www.facebook.com/cnnpolitics/posts/128...  mostly true    59    10   
4  https://www.facebook.com/cnnpolitics/posts/128...  mostly true   462    12   

   Love  Sad  Wow  Angry  
0     0    0    0      3  
1     2    0    0      0  
2    42    0    0     21  
3     0    0    0     12  
4    25    0    0      0

In [14]:


x_t = data.iloc[:,4].values



a = x_t[0].lower()



a = re.sub(r'\d+', '', a)



a = a.strip()



a = a.translate(str.maketrans('','', string.punctuation))



stop_words = set(stopwords.words('english'))



tokens = word_tokenize(a)
result = [i for i in tokens if not i in stop_words]



lemmatizer=WordNetLemmatizer()
lemat = []
for word in result:
    lemat.append(lemmatizer.lemmatize(word))

stri = ""
for i in lemat:
    stri = stri + i + " "



print(stri)

corpus = []
stop_words = set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()
for k in x_t:
    a = k.lower()
    a = re.sub(r'\d+', '', a)
    a = a.strip()
    a = a.translate(str.maketrans('','', string.punctuation))
    stop_words = set(stopwords.words('english'))
    tokens = word_tokenize(a)
    result = [i for i in tokens if not i in stop_words]
    lemat = []
    for word in result:
        lemat.append(lemmatizer.lemmatize(word))
    stri = ""
    for i in lemat:
        stri = stri + i + " "
    corpus.append(stri)



len(corpus)




from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
x= tf.fit_transform(corpus).toarray()




y_t = data.iloc[:,7].values




type(y_t)



y_t.shape



from collections import Counter
y_t = y_t.tolist()
b = Counter(y_t).keys()

b

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_y = LabelEncoder()
y_t = labelencoder_y.fit_transform(y_t)


name comment jonathan del carmen jonathan del carmen hillary clinton lead jack schroth jack schroth strategy bring mu lisa bivona lisa bivona melinda maynard hyatt lol suzie sevigny suzie sevigny time america anthony colón anthony colón gary johnson american busi jonathan del carmen jonathan del carmen hillary clinton still lead mickey shay mickey shay here debate strategynletgary delina hess blanchett delina hess blanchett medium atten darrell blaser darrell blaser banned documentary episode dave anderson dave anderson cnn anti america digusting titi oshodi titi oshodi get education stop repeating lie billy master billy master httplfacebookcomlphp john sparacio john sparacio plan call total amnest darrell blaser darrell blaser black man trump shirt confro melinda hyatt melinda hyatt wikileaks confirms hillary sol chad smith chad smith cnn protrump ashley mulder ashley mulder practice saying yuuuuuge th rebecca laskey rebecca laskey republican businessman donald j danette ej danette ej

In [15]:


print(y_t)


# In[225]:


y_t = y_t.reshape(-1,1)
print(y_t)


# In[226]:


onehotencoder_y = OneHotEncoder()
y_t = onehotencoder_y.fit_transform(y_t)


# In[227]:


print(y_t)


# In[228]:


y_t = y_t.toarray()
y1_t= y_t


# In[229]:


print(y_t)


# In[195]:


#type(y_t)
#import numpy as np
#y_t = np.delete(y_t,y_t.shape[1]-1,axis=1)


# In[196]:


print(y_t)


# In[230]:


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y_t, test_size=0.25, random_state=0)


# In[231]:


from sklearn.svm import SVC
from skmultilearn.problem_transform import LabelPowerset
from sklearn.model_selection import cross_validate
classifier2 = LabelPowerset(SVC(kernel = 'rbf',probability=True, random_state = 0,gamma='auto'))
classifier2.fit(X_train,y_train)
scores = cross_validate(classifier2,X_train,y_train,cv=5)
print(scores)


# In[235]:


y_pred = classifier2.predict(X_test)
y1_pred = classifier2.predict(X_train)
print(y1_pred.shape)



[1 1 1 1 1 1 1 1 1 1 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 0 2 2 0 2 2 2 2 2 2 2
 2 2 2 2 0 2 0 2 2 2 2 2 0 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 2 1 2 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2
 0 0 0 2 2 2]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [0]
 [2]
 [2]
 [2]
 

C:\Users\goels\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


{'fit_time': array([1.95621037, 1.74549198, 2.00658464, 1.90198493, 1.6050837 ]), 'score_time': array([0.09271073, 0.09984303, 0.08183932, 0.0885129 , 0.07477212]), 'test_score': array([0.92647059, 0.86764706, 0.85074627, 0.88059701, 0.7761194 ])}
(337, 3)


In [5]:
print(y_pred)


  (0, 1)	1
  (1, 1)	1
  (2, 1)	1
  (3, 1)	1
  (4, 1)	1
  (5, 1)	1
  (6, 1)	1
  (7, 1)	1
  (8, 1)	1
  (9, 1)	1
  (10, 1)	1
  (11, 1)	1
  (12, 1)	1
  (13, 1)	1
  (14, 1)	1
  (15, 1)	1
  (16, 1)	1
  (17, 1)	1
  (18, 1)	1
  (19, 1)	1
  (20, 1)	1
  (21, 1)	1
  (22, 1)	1
  (23, 1)	1
  (24, 1)	1
  (25, 1)	1
  (26, 1)	1
  (27, 1)	1
  (28, 1)	1
  (29, 1)	1
  (30, 1)	1
  (31, 1)	1
  (32, 1)	1
  (33, 1)	1
  (34, 1)	1
  (35, 1)	1
  (36, 1)	1
  (37, 1)	1
  (38, 1)	1
  (39, 1)	1
  (40, 1)	1
  (41, 1)	1
  (42, 1)	1
  (43, 1)	1
  (44, 1)	1
  (45, 1)	1
  (46, 1)	1
  (47, 1)	1
  (48, 1)	1
  (49, 1)	1
  (50, 1)	1
  (51, 1)	1
  (52, 1)	1
  (53, 1)	1
  (54, 1)	1
  (55, 1)	1
  (56, 1)	1
  (57, 1)	1
  (58, 1)	1
  (59, 1)	1
  (60, 1)	1
  (61, 1)	1
  (62, 1)	1
  (63, 1)	1
  (64, 1)	1
  (65, 1)	1
  (66, 1)	1
  (67, 1)	1
  (68, 1)	1
  (69, 1)	1
  (70, 1)	1
  (71, 1)	1
  (72, 1)	1
  (73, 1)	1
  (74, 1)	1
  (75, 1)	1
  (76, 1)	1
  (77, 1)	1
  (78, 1)	1
  (79, 1)	1
  (80, 1)	1
  (81, 1)	1
  (82, 1)	1
  (83, 1)	1
  

In [16]:


print(y_pred[99])


# In[246]:


a=y_pred.toarray()

b= y1_pred.toarray()
# In[247]:


a


# In[248]:


from sklearn.metrics import accuracy_score,precision_score,recall_score


# In[249]:


acc = accuracy_score(y_test, y_pred)


# In[250]:


precision = precision_score(y_test, y_pred, average='micro')


# In[251]:


recall = recall_score(y_test, y_pred, average='micro')


# In[252]:


acc,precision,recall


# In[254]:

#y = dataset.iloc[:, 8].values


# In[255]:




  (0, 1)	1


(0.8672566371681416, 0.8672566371681416, 0.8672566371681416)

In [17]:
a

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [18]:
b

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]], dtype=int64)

In [19]:
l=[]
for i in b:
    l.append(i)
for i in a:
    l.append(i)

In [20]:
(l[0])[0]
import numpy as np
f = np.empty([450,3])

In [21]:
for i in range(0,450):
    for j in range(0,3):
        f[i][j] = (l[i])[j]

In [22]:
f[29][1]

1.0

In [23]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(classifier2) 
  

In [24]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [25]:
dataset = pd.read_csv('f_dataf.csv')
"""column = [2,3,4,9,10,11,12,13,14,15,16,17]
X1 = dataset.iloc[:, column].values
ynn = dataset.iloc[:, 8].values"""

'column = [2,3,4,9,10,11,12,13,14,15,16,17]\nX1 = dataset.iloc[:, column].values\nynn = dataset.iloc[:, 8].values'

In [26]:
svm1=[]
svm2=[]
svm3=[]
for i in range(0,450):
    svm1.append(f[i][0])
    svm2.append(f[i][1])
    svm3.append(f[i][2])
    
# len(svm3)
dataset['svm1']=svm1
dataset['svm2']=svm2
dataset['svm3']=svm3

In [27]:
column = [2,3,4,9,10,11,12,13,14,15,16,17]
X1 = dataset.iloc[:, column].values
ynn = dataset.iloc[:, 8].values

In [28]:
for i in range(0,400):
    if(float(X1[i][0])!= 0):
        (X1[i][3])=float(X1[i][3])/float(X1[i][0])
        (X1[i][4])=float(X1[i][4])/float(X1[i][0])
        (X1[i][5])=float(X1[i][5])/float(X1[i][0])
        (X1[i][6])=float(X1[i][6])/float(X1[i][0])
        (X1[i][7])=float(X1[i][7])/float(X1[i][0])
        (X1[i][8])=float(X1[i][8])/float(X1[i][0])
        # np.append(X1[i],[f[i][0],f[i][1],f[i][2]])



In [29]:
X1

array([[5.80e+01, 1.03e+02, 8.00e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [3.30e+01, 6.40e+01, 6.00e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [4.97e+02, 3.83e+02, 1.11e+02, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       ...,
       [4.00e+03, 3.40e+02, 0.00e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [3.80e+04, 1.50e+03, 0.00e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [3.50e+04, 1.60e+03, 0.00e+00, ..., 0.00e+00, 1.00e+00, 0.00e+00]])

In [30]:
# for i in range(0,400):
#     X2.append([X1[i][0],X1[i][1],X1[i][2],X1[i][3],X1[i][4],X1[i][5],X1[i][6],X1[i][7],X1[i][8],f[i][0],f[i][1],f[i][2]])
#X3=pd.DataFrame(X2,columns=[0,1,2,3,4,5,6,7,8,9,10,11]) 

In [337]:
# X2

In [338]:
#X2.remove([])
#print(X2.tolist())
# X3 = np.array(X2)

In [339]:
# X3

In [340]:
# X4=X3[:400]

In [31]:
# X4[399]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y_t, test_size=0.25, random_state=0)


In [32]:
from sklearn.model_selection import train_test_split
d_train, d_test, y_train, y_test = train_test_split(X1, y_t, test_size=0.25, random_state=0)


In [33]:
from sklearn.svm import SVC
from skmultilearn.problem_transform import LabelPowerset
from sklearn.model_selection import cross_validate
classifier3 = LabelPowerset(SVC(kernel = 'rbf',probability=True, random_state = 0,gamma='auto'))
classifier3.fit(d_train,y_train)
scores = cross_validate(classifier3,d_train,y_train,cv=5)
print(scores)


# In[235]:


y_pred = classifier3.predict(d_test)
y1_pred = classifier3.predict(d_train)
print(y1_pred)

{'fit_time': array([0.04841089, 0.04562855, 0.04944372, 0.04394102, 0.04844475]), 'score_time': array([0.00801539, 0.00399518, 0.0039947 , 0.00799108, 0.00399518]), 'test_score': array([0.92647059, 0.86764706, 0.85074627, 0.88059701, 0.7761194 ])}
  (0, 1)	1
  (1, 2)	1
  (2, 1)	1
  (3, 1)	1
  (4, 2)	1
  (5, 1)	1
  (6, 1)	1
  (7, 1)	1
  (8, 1)	1
  (9, 1)	1
  (10, 1)	1
  (11, 1)	1
  (12, 1)	1
  (13, 1)	1
  (14, 1)	1
  (15, 1)	1
  (16, 1)	1
  (17, 1)	1
  (18, 1)	1
  (19, 1)	1
  (20, 1)	1
  (21, 1)	1
  (22, 1)	1
  (23, 1)	1
  (24, 1)	1
  (25, 1)	1
  (26, 1)	1
  (27, 1)	1
  (28, 1)	1
  (29, 1)	1
  (30, 1)	1
  (31, 1)	1
  (32, 1)	1
  (33, 1)	1
  (34, 1)	1
  (35, 1)	1
  (36, 1)	1
  (37, 1)	1
  (38, 1)	1
  (39, 1)	1
  (40, 1)	1
  (41, 1)	1
  (42, 1)	1
  (43, 2)	1
  (44, 1)	1
  (45, 1)	1
  (46, 1)	1
  (47, 1)	1
  (48, 1)	1
  (49, 1)	1
  (50, 1)	1
  (51, 1)	1
  (52, 1)	1
  (53, 1)	1
  (54, 1)	1
  (55, 1)	1
  (56, 1)	1
  (57, 1)	1
  (58, 2)	1
  (59, 1)	1
  (60, 1)	1
  (61, 1)	1
  (62, 2)	1
  (63,

In [344]:
from sklearn.metrics import accuracy_score,precision_score,recall_score


# In[249]:


acc = accuracy_score(y_test, y_pred)


# In[250]:


precision = precision_score(y_test, y_pred, average='micro')


# In[251]:


recall = recall_score(y_test, y_pred, average='micro')


# In[252]:


acc,precision,recall



(0.8761061946902655, 0.8761061946902655, 0.8761061946902655)

In [34]:
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
ynn= label_encoder.fit_transform(ynn) 

In [35]:
from keras.utils import to_categorical
ynn = to_categorical(ynn)

In [36]:



from sklearn.model_selection import train_test_split
d_train, d_test, ynn_train, ynn_test = train_test_split(X1, ynn, test_size=0.25, random_state=0)

print(d_train.shape)
# In[57]:



# In[49]:



(337, 12)


In [37]:
def model():
    classifier = Sequential()

    # Adding the input layer and the first hidden layer
    classifier.add(Dense(units = 7, kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim = 12))

    # Adding the second hidden layer
    classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'relu'))

    # Adding the output layer
    classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'softmax'))

    # Compiling the ANN
    #classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    classifier.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    # Fitting the ANN to the Training set
    classifier.fit(d_train, ynn_train, batch_size = 10, epochs = 100)
    return classifier

In [38]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from keras.wrappers.scikit_learn import KerasClassifier

from sklearn.model_selection import train_test_split

#print(d_train.shape)
#kfold = KFold(n_splits=10, shuffle=True)
classifier = KerasClassifier(build_fn=model,batch_size = 5, epochs = 150)
results = cross_val_score(estimator=classifier, X=d_train, y=ynn_train, cv=10,n_jobs=-1)
print(results.mean())

0.9164884030818939


In [39]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(classifier)